name: background_print
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter:
    sdk: flutter
  collection: ^1.18.0
  dio: ^5.5.0+1
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1

  intl: ^0.19.0
  shimmer: ^3.0.0
  logger: ^2.3.0
  flutter_background_service: 5.0.5
  flutter_background_service_android: 6.2.2
  flutter_launcher_icons: ^0.11.0
  image: ^3.3.0

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#6A3DE8"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true
flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/icon.png
  color_dark: "#6A3DE8"
  fullscreen: true
  color: "#022200"
  android_12:
    color: "#6A3DE8"
    image: assets/icon.png
    color_dark: "#6A3DE8"
  android_gravity: center
  ios_content_mode: center

assets:
  - assets/
flutter:
  uses-material-design: true
